"""
Module: transform.py
Author: Senior Data Engineering Mentor (Amazon RBS Portfolio Project)
Description: Production-hardened transformation engine utilizing PySpark for distributed 
             in-memory cleaning and PyArrow for native Windows Parquet output.
"""

import os
import glob
from datetime import datetime
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, IntegerType
from pyspark.sql.functions import col, to_timestamp, current_timestamp, lit

# Define explicit paths relative to script location
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INGRESS_DIR = os.path.join(BASE_DIR, "data", "ingress")
CLEAN_OUTPUT_DIR = os.path.join(BASE_DIR, "data", "silver_clean")
DLQ_OUTPUT_DIR = os.path.join(BASE_DIR, "data", "dlq_defects")

def get_latest_ingress_file():
    """Finds the freshest dataset generated by the upstream ingestion layer."""
    search_path = os.path.join(INGRESS_DIR, "catalog_transactions_*.csv")
    files = glob.glob(search_path)
    if not files:
        raise FileNotFoundError(f"❌ No ingestion file found in {INGRESS_DIR}. Run data_generator.py first.")
    return max(files, key=os.path.getctime)

def main():
    print(f"🚀 Initializing PySpark Processing Core at: {datetime.now()}")
    
    # Force complete Windows local networking loopback properties
    os.environ["SPARK_LOCAL_IP"] = "127.0.0.1"

    # 1. Initialize Local Spark Session (Optimized for safe in-memory validation)
    spark = SparkSession.builder \
        .appName("Amazon-RBS-Data-Quality-Pipeline") \
        .master("local[*]") \
        .config("spark.sql.execution.arrow.pyspark.enabled", "true") \
        .getOrCreate()
        
    spark.sparkContext.setLogLevel("WARN")

    # 2. Define Explicit Ingress Schema
    ingress_schema = StructType([
        StructField("transaction_id", StringType(), True),
        StructField("product_id", StringType(), True),
        StructField("merchant_id", StringType(), True),
        StructField("category", StringType(), True),
        StructField("marketplace_region", StringType(), True),
        StructField("price", StringType(), True), 
        StructField("quantity", IntegerType(), True),
        StructField("transaction_date", StringType(), True),
        StructField("ingest_timestamp", StringType(), True)
    ])

    # 3. Read Ingress Data
    try:
        input_file = get_latest_ingress_file()
        print(f"📖 Ingesting file: {input_file}")
    except FileNotFoundError as e:
        print(str(e))
        spark.stop()
        return
    
    raw_df = spark.read \
        .option("header", "true") \
        .schema(ingress_schema) \
        .csv(input_file)

    # Cache incoming data for multi-branch optimization
    raw_df.cache()
    total_count = raw_df.count()

    # 4. Normalize Formats & Add Audit Metadata
    normalized_df = raw_df \
        .withColumn("transaction_date_parsed", to_timestamp(col("transaction_date"), "yyyy-MM-dd HH:mm:ss")) \
        .withColumn("numeric_price", col("price").cast(DoubleType())) \
        .withColumn("processed_at", current_timestamp())

    # 5. Define Data Quality Guardrails 
    allowed_categories = ['Electronics', 'Apparel', 'Home & Kitchen', 'Automotive', 'Books', 'Beauty']
    # 6. Define Data Quality Guardrails (Amazon RBS Defect Rules)
    is_defective = (
        col("product_id").isNull() | 
        col("numeric_price").isNull() | 
        (col("quantity") < 0) | 
        (col("transaction_date_parsed") > col("processed_at")) |
        col("price").rlike("[^0-9.]") |
        (col("numeric_price")>5000) |
        (~col("category").isin(allowed_categories))

    )

    # 6. Branch Data Pipeline (Clean Production vs. Dead-Letter Queue)
    clean_df = normalized_df.filter(~is_defective) \
        .select(
            col("transaction_id"), col("product_id"), col("merchant_id"),
            col("category"), col("marketplace_region"),
            col("numeric_price").alias("price"), col("quantity"),
            col("transaction_date_parsed").alias("transaction_date")
        )

    dlq_df = normalized_df.filter(is_defective) \
        .withColumn("defect_logged_date", lit(datetime.now().strftime("%Y-%m-%d"))) \
        .select(
            "transaction_id", "product_id", "merchant_id", "category", 
            "marketplace_region", "price", "quantity", "transaction_date", 
            "defect_logged_date"
        )

    # 7. Convert to optimized local Pandas context to bypass Java/Hadoop storage issues
    print(f"🔄 Bridging distributed datasets to secure file-system driver...")
    clean_pd = clean_df.toPandas()
    dlq_pd = dlq_df.toPandas()

    # 8. Write Clean Data to Parquet using PyArrow Engine
    print(f"💾 Committing verified records to Silver Layer: {CLEAN_OUTPUT_DIR}")
    os.makedirs(CLEAN_OUTPUT_DIR, exist_ok=True)
    clean_target = os.path.join(CLEAN_OUTPUT_DIR, "clean_catalog_transactions.parquet")
    clean_pd.to_parquet(clean_target, engine='pyarrow', compression='snappy', index=False)

    # 9. Write Defective Records to Dead Letter Queue 
    print(f"⚠️ Committing defective rows to DLQ Target: {DLQ_OUTPUT_DIR}")
    os.makedirs(DLQ_OUTPUT_DIR, exist_ok=True)
    dlq_target = os.path.join(DLQ_OUTPUT_DIR, "defective_catalog_transactions.parquet")
    dlq_pd.to_parquet(dlq_target, engine='pyarrow', compression='snappy', index=False)

    # Log operational metrics for monitoring aggregation
    print("\n" + "="*40)
    print("      PIPELINE EXECUTION METRICS")
    print("="*40)
    print(f" Total Rows Ingested:      {total_count:,}")
    print(f" Clean Rows Curated:       {len(clean_pd):,}")
    print(f" Defective Rows Isolated:  {len(dlq_pd):,}")
    print("="*40 + "\n")

    spark.stop()
    print("✅ PySpark Engine shut down cleanly.")

if __name__ == "__main__":
    main()